language: node_js
node_js:
  - "10.15"

install:
  - npm ci
  - npm i -g @angular/cli

branches:
  only:
    - master
    - /^IO2019TEAM-.*$/

script:
  - npm run generate.declarations
  - npm run build
  - npm run lint
